import { Image, StyleSheet, Text, View } from "@react-pdf/renderer";

export const colors = {
  ink: "#111827",
  subtle: "#6b7280",
  border: "#e5e7eb",
  panel: "#f9fafb",
};

export const sharedStyles = StyleSheet.create({
  page: { padding: 40, paddingBottom: 72, fontSize: 10, fontFamily: "Helvetica", color: colors.ink },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  logo: { width: 36, height: 36, marginBottom: 6, objectFit: "contain" },
  companyName: { fontSize: 16, fontFamily: "Helvetica-Bold" },
  companyMeta: { fontSize: 8, color: colors.subtle, marginTop: 2 },
  docTitle: { fontSize: 18, fontFamily: "Helvetica-Bold", textAlign: "right" },
  docMeta: { fontSize: 8, color: colors.subtle, textAlign: "right", marginTop: 2 },
  divider: { borderBottomWidth: 1, borderBottomColor: colors.border, marginBottom: 16 },
  sectionTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: colors.subtle,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 16,
    marginBottom: 8,
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
  },
  footerText: { fontSize: 8, color: colors.subtle },
  pageNumber: { position: "absolute", bottom: 32, right: 40, fontSize: 8, color: colors.subtle },
});

type PdfHeaderProps = {
  kind: string;
  companyName: string;
  trade?: string | null;
  companyNumber?: string | null;
  vatNumber?: string | null;
  brandColor?: string;
  logoUrl?: string;
  reference: string;
  date: string;
};

export const PdfHeader = ({
  kind,
  companyName,
  trade,
  companyNumber,
  vatNumber,
  brandColor = "#111827",
  logoUrl,
  reference,
  date,
}: PdfHeaderProps) => (
  <View style={sharedStyles.headerRow}>
    <View>
      {/* eslint-disable-next-line jsx-a11y/alt-text -- @react-pdf/renderer's Image, not an HTML img */}
      {logoUrl && <Image src={logoUrl} style={sharedStyles.logo} />}
      <Text style={[sharedStyles.companyName, { color: brandColor }]}>{companyName}</Text>
      {(trade || companyNumber || vatNumber) && (
        <Text style={sharedStyles.companyMeta}>
          {[trade, companyNumber ? `Co. No. ${companyNumber}` : null, vatNumber ? `VAT ${vatNumber}` : null]
            .filter(Boolean)
            .join("   ·   ")}
        </Text>
      )}
    </View>
    <View>
      <Text style={sharedStyles.docTitle}>{kind}</Text>
      <Text style={sharedStyles.docMeta}>Ref {reference}</Text>
      <Text style={sharedStyles.docMeta}>{date}</Text>
    </View>
  </View>
);

export const PdfFooter = ({ note }: { note?: string }) => (
  <View style={sharedStyles.footer} fixed>
    {note && <Text style={sharedStyles.footerText}>{note}</Text>}
    <Text style={sharedStyles.footerText}>Generated by Motko</Text>
  </View>
);
