/**
 * The documents and the app are ONE visual system.
 *
 * The quote, statement of work and contract ran a navy-grey palette —
 * #111827 / #6b7280 / #e5e7eb / #f9fafb — unrelated to anything on screen, on
 * the only artefacts a customer keeps. That was half of "two visual systems in
 * one product".
 *
 * @react-pdf/renderer resolves no CSS custom properties, so `colors` in
 * pdf/shared.tsx must hold literals; it cannot say `var(--ink)`. This is what
 * stops those literals and the tokens they copy from drifting apart — the one
 * failure mode a hand-copied palette has.
 *
 * It also holds the print type floor, which lives here rather than in the
 * off-token guard because points and pixels are different units with different
 * floors: 12pt in print, 12px on screen.
 */
import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { colors } from "@/lib/pdf/shared";

const SRC = resolve(__dirname, "../../src");
const PDF_DIR = join(SRC, "lib/pdf");

const globalsCss = (): string => readFileSync(join(SRC, "app/globals.css"), "utf8");

/** The resolved value of a token as `:root` declares it. */
const token = (name: string): string => {
  const match = globalsCss().match(
    new RegExp(`--${name}:\\s*(#[0-9a-fA-F]{3,8})`),
  );
  expect(match, `--${name} not found in globals.css`).toBeTruthy();
  return match![1].toLowerCase();
};

const pdfSources = (): string[] =>
  readdirSync(PDF_DIR)
    .filter((f) => /\.tsx?$/.test(f) && !f.includes(".test."))
    .map((f) => readFileSync(join(PDF_DIR, f), "utf8"));

describe("the document palette IS the app palette", () => {
  it("maps every document colour onto the token it copies", () => {
    expect(colors.ink).toBe(token("ink"));
    expect(colors.subtle).toBe(token("ink-secondary"));
    expect(colors.border).toBe(token("line-strong"));
    expect(colors.panel).toBe(token("ground"));
    expect(colors.green).toBe(token("green"));
  });

  it("keeps the old navy system out of every renderer", () => {
    const navy = /#111827|#6b7280|#e5e7eb|#f9fafb/;
    for (const source of pdfSources()) {
      // Comments stripped: shared.tsx names the retired values in prose to say
      // what they were, which is worth keeping and is not a usage.
      const code = source
        .replace(/\/\*[\s\S]*?\*\//g, "")
        .replace(/^\s*\/\/.*$/gm, "");
      expect(code).not.toMatch(navy);
    }
  });
});

describe("the print type floor", () => {
  it("sets nothing below 12pt", () => {
    // "Minimum 12pt body in print" — the 8pt italic captions on a document a
    // customer keeps were the case that made this a rule. A floor, not a
    // clamp: the sizes above it still differ, or the document has no
    // hierarchy left.
    const offenders: string[] = [];
    for (const source of pdfSources()) {
      for (const [, size] of source.matchAll(/fontSize: (\d+(?:\.\d+)?)/g)) {
        if (Number(size) < 12) offenders.push(size);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("still has more than one size, so the floor did not flatten it", () => {
    const sizes = new Set<string>();
    for (const source of pdfSources()) {
      for (const [, size] of source.matchAll(/fontSize: (\d+(?:\.\d+)?)/g)) {
        sizes.add(size);
      }
    }
    expect(sizes.size).toBeGreaterThan(3);
  });
});

describe("a document says a thing once", () => {
  it("prints no second footer beside the maker's mark", () => {
    // Comments stripped: shared.tsx names the retired string in prose to say
    // what was removed and why, which is worth keeping and is not a usage.
    for (const source of pdfSources()) {
      const code = source
        .replace(/\/\*[\s\S]*?\*\//g, "")
        .replace(/^\s*\/\/.*$/gm, "");
      expect(code).not.toContain("Generated by Motko");
    }
  });

  it("only italicises text the contract's own author italicised", () => {
    // `styles.italic` in contract-pdf renders parsed *emphasis* from contract
    // text — content markup, exempt. Any OTHER fontStyle: "italic" is a
    // styling decision and is not allowed.
    const all = pdfSources().join("\n");
    const italics = all.match(/fontStyle: "italic"/g) ?? [];
    expect(italics).toHaveLength(1);
  });
});
